INSERT INTO USER (USERID, NAME, LASTNAME, SECONDNAME, PASSWORD, EDGE, ISACCOUNTNONEXPIRED, ISACCOUNTNONLOCKED, ISCREDENTIALSNONEXPIRED, ISENABLED) 
VALUES ('user3', 'user3', 'user3', 'user3', '$2a$12$1qhi5PhMMe/TrCpJY0zM3OutWSDbvcGIE7eyxr.jkc4Efb2y8df.G', '23', 'true', 'true', 'true', 'true');--user3
INSERT INTO USER (USERID, NAME, LASTNAME, SECONDNAME, PASSWORD, EDGE, ISACCOUNTNONEXPIRED, ISACCOUNTNONLOCKED, ISCREDENTIALSNONEXPIRED, ISENABLED) 
VALUES ('user4', 'user4', 'user4', 'user4', '$2a$12$enTDCOM9Gt8JB0HIxYdPAu2d8FVuDkN6HsuPoqWIko.W9UY5oFFL6', '24', 'true', 'true', 'true', 'true');--user4

INSERT INTO AUTH_USER_GROUP (USERID, AUTH_GROUP) VALUES('user3', 'ROLE_ADMIN');
INSERT INTO AUTH_USER_GROUP (USERID, AUTH_GROUP) VALUES('user4', 'ROLE_USER');

--https://bcrypt-generator.com/