version: 0.0
os: linux
files:
- source: lab1.jar
  destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
  - location: scripts/install_java
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_app
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop_app
    timeout: 300
    runas: root