version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      # create start_app file
      - echo "#!/bin/bash" >> src/main/resources/aws-config/scripts/start_app
      - echo "export APP_CONFIG_IMAGE_AWS_ACCESSKEY='${APP_CONFIG_IMAGE_AWS_ACCESSKEY}'" >> src/main/resources/aws-config/scripts/start_app
      - echo "export APP_CONFIG_IMAGE_AWS_SECRETKEY='${APP_CONFIG_IMAGE_AWS_SECRETKEY}'" >> src/main/resources/aws-config/scripts/start_app
      - echo "export AZURE_STORAGE_CONNECTION_STRING='${AZURE_STORAGE_CONNECTION_STRING}'" >> src/main/resources/aws-config/scripts/start_app
      - echo "export SPRING_PROFILES_ACTIVE='${PROFILE_ACTIVE}'" >> src/main/resources/aws-config/scripts/start_app
      - echo "java -jar /home/ec2-user/javaapp/lab1.jar" >> src/main/resources/aws-config/scripts/start_app
      # Move source files to root directory.
      - cp src/main/resources/aws-config/template.yml ./template.yml  
      - cp src/main/resources/aws-config/appspec.yml ./appspec.yml  
      - cp -R src/main/resources/aws-config/scripts ./scripts  
      - cp target/lab1-0.0.1-SNAPSHOT.jar ./lab1.jar  
artifacts:
  files:
    - lab1.jar
    - template.yml
    - scripts/*
    - appspec.yml
