trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-variable-group

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
  displayName: 'Maven'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    #pathToSources: '${System.DefaultWorkingDirectory}/src/main/java/'
    reportDirectory: '${System.DefaultWorkingDirectory}/target/site/jacoco/**'
    additionalCodeCoverageFiles: '${System.DefaultWorkingDirectory}/target/jacoco.exec'
    failIfCoverageEmpty: true
  displayName: 'JaCoCo'
- task: Bash@3
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)/target/app-srv-plan-setup.sh'
    workingDirectory: '$(System.DefaultWorkingDirectory)/target/'
    failOnStderr: true
  displayName: 'Creation App service plan'