trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: MavenJob
  #timeoutInMinutes: 10
  steps:
  - task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    
- job: Secondjob
  steps:
  - bash: echo "The Second job"