trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube-connection'
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=Spring-lab'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test install sonar:sonar package'
    #options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'SpringLabTest'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    #pathToSources: '${System.DefaultWorkingDirectory}/src/main/java/'
    reportDirectory: '${System.DefaultWorkingDirectory}/target/site/jacoco'
    additionalCodeCoverageFiles: '${System.DefaultWorkingDirectory}/target/jacoco.exec'
    failIfCoverageEmpty: true

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'