trigger:
- feature/Implementing-azure-pipeline
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: Firstjob
  timeoutInMinutes: 10
  steps:
  - bash: echo "The Fisrt job"

- job: Secondjob
  steps:
  - bash: echo "The Second job"